Repository OCA/hr-expense, pull requests merged in 2020-10, with the labels that each got.

#9 [FIX] hr_expense_advance_clearing: analytic account visibility
  hr_expense_advance_clearing/README.rst
  hr_expense_advance_clearing/readme/CONTRIBUTORS.rst
  hr_expense_advance_clearing/static/description/index.html
  hr_expense_advance_clearing/views/hr_expense_views.xml
Labels: bot is merging ⏳

#4 [13.0][MIG] hr_expense_sequence
  hr_expense_sequence/README.rst
  hr_expense_sequence/__init__.py
  hr_expense_sequence/__manifest__.py
  hr_expense_sequence/data/hr_expense_data.xml
  hr_expense_sequence/hooks.py
  hr_expense_sequence/i18n/cs_CZ.po
  hr_expense_sequence/i18n/de.po
  hr_expense_sequence/i18n/es.po
  hr_expense_sequence/i18n/fi.po
  hr_expense_sequence/i18n/fr.po
  hr_expense_sequence/i18n/hr.po
  hr_expense_sequence/i18n/hr_expense_sequence.pot
  hr_expense_sequence/i18n/it.po
  hr_expense_sequence/i18n/nl_NL.po
  hr_expense_sequence/i18n/pt_BR.po
  hr_expense_sequence/i18n/sl.po
  hr_expense_sequence/models/__init__.py
  hr_expense_sequence/models/hr_expense_sheet.py
  hr_expense_sequence/readme/CONFIGURE.rst
  hr_expense_sequence/readme/CONTRIBUTORS.rst
  hr_expense_sequence/readme/DESCRIPTION.rst
  hr_expense_sequence/report/report_expense_sheet.xml
  hr_expense_sequence/static/description/icon.png
  hr_expense_sequence/static/description/index.html
  hr_expense_sequence/tests/__init__.py
  hr_expense_sequence/tests/test_hr_expense_sequence.py
  hr_expense_sequence/views/hr_expense_expense_view.xml
  setup/hr_expense_sequence/odoo/addons/hr_expense_sequence
  setup/hr_expense_sequence/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#13 [14.0][MIG] hr_expense_sequence
  hr_expense_sequence/README.rst
  hr_expense_sequence/__init__.py
  hr_expense_sequence/__manifest__.py
  hr_expense_sequence/data/hr_expense_data.xml
  hr_expense_sequence/hooks.py
  hr_expense_sequence/i18n/cs_CZ.po
  hr_expense_sequence/i18n/de.po
  hr_expense_sequence/i18n/es.po
  hr_expense_sequence/i18n/fi.po
  hr_expense_sequence/i18n/fr.po
  hr_expense_sequence/i18n/hr.po
  hr_expense_sequence/i18n/hr_expense_sequence.pot
  hr_expense_sequence/i18n/it.po
  hr_expense_sequence/i18n/nl_NL.po
  hr_expense_sequence/i18n/pt_BR.po
  hr_expense_sequence/i18n/sl.po
  hr_expense_sequence/models/__init__.py
  hr_expense_sequence/models/hr_expense_sheet.py
  hr_expense_sequence/readme/CONFIGURE.rst
  hr_expense_sequence/readme/CONTRIBUTORS.rst
  hr_expense_sequence/readme/DESCRIPTION.rst
  hr_expense_sequence/report/report_expense_sheet.xml
  hr_expense_sequence/static/description/icon.png
  hr_expense_sequence/static/description/index.html
  hr_expense_sequence/tests/__init__.py
  hr_expense_sequence/tests/test_hr_expense_sequence.py
  hr_expense_sequence/views/hr_expense_expense_view.xml
  setup/hr_expense_sequence/odoo/addons/hr_expense_sequence
  setup/hr_expense_sequence/setup.py
Labels: approved, bot is merging ⏳

#8 [13.0][MIG] hr_expense_payment_difference
  hr_expense_payment_difference/README.rst
  hr_expense_payment_difference/__init__.py
  hr_expense_payment_difference/__manifest__.py
  hr_expense_payment_difference/i18n/hr_expense_payment_difference.pot
  hr_expense_payment_difference/models/__init__.py
  hr_expense_payment_difference/models/account_payment.py
  hr_expense_payment_difference/models/hr_expense.py
  hr_expense_payment_difference/readme/CONTRIBUTORS.rst
  hr_expense_payment_difference/readme/DESCRIPTION.rst
  hr_expense_payment_difference/readme/USAGE.rst
  hr_expense_payment_difference/static/description/icon.png
  hr_expense_payment_difference/static/description/index.html
  hr_expense_payment_difference/tests/__init__.py
  hr_expense_payment_difference/tests/test_hr_expense_payment_difference.py
  hr_expense_payment_difference/wizards/__init__.py
  hr_expense_payment_difference/wizards/hr_expense_sheet_register_payment.py
  hr_expense_payment_difference/wizards/hr_expense_sheet_register_payment.xml
  setup/hr_expense_payment_difference/odoo/addons/hr_expense_payment_difference
  setup/hr_expense_payment_difference/setup.py
Labels: approved, bot is merging ⏳
