Repository OCA/hr-expense, pull requests merged in 2021-12, with the labels that each got.

#84 [14.0][ADD] hr_expense_journal
  hr_expense_journal/__init__.py
  hr_expense_journal/__manifest__.py
  hr_expense_journal/models/__init__.py
  hr_expense_journal/models/hr_expense.py
  hr_expense_journal/readme/CONTRIBUTORS.rst
  hr_expense_journal/readme/DESCRIPTION.rst
  hr_expense_journal/readme/USAGE.rst
  hr_expense_journal/views/hr_expense_views.xml
  setup/hr_expense_journal/odoo/addons/hr_expense_journal
  setup/hr_expense_journal/setup.py
Labels: approved, bot is merging ⏳

#46 [14.0][ADD] hr_expense_exception
  hr_expense_exception/__init__.py
  hr_expense_exception/__manifest__.py
  hr_expense_exception/data/expense_sheet_exception_data.xml
  hr_expense_exception/models/__init__.py
  hr_expense_exception/models/exception_rule.py
  hr_expense_exception/models/hr_expense.py
  hr_expense_exception/models/hr_expense_sheet.py
  hr_expense_exception/readme/CONTRIBUTORS.rst
  hr_expense_exception/readme/DESCRIPTION.rst
  hr_expense_exception/security/ir.model.access.csv
  hr_expense_exception/static/description/icon.png
  hr_expense_exception/tests/__init__.py
  hr_expense_exception/tests/test_expense_sheet_exception.py
  hr_expense_exception/views/hr_expense_view.xml
  hr_expense_exception/wizard/__init__.py
  hr_expense_exception/wizard/expense_sheet_exception_confirm.py
  hr_expense_exception/wizard/expense_sheet_exception_confirm_view.xml
  setup/hr_expense_exception/odoo/addons/hr_expense_exception
  setup/hr_expense_exception/setup.py
Labels: approved, bot is merging ⏳

#69 [13.0][MIG] hr_expense_portal: Migration to 13.0
  hr_expense_portal/README.rst
  hr_expense_portal/__init__.py
  hr_expense_portal/__manifest__.py
  hr_expense_portal/controllers/__init__.py
  hr_expense_portal/controllers/expense_portal.py
  hr_expense_portal/readme/CONTRIBUTORS.rst
  hr_expense_portal/readme/CREDITS.rst
  hr_expense_portal/readme/DESCRIPTION.rst
  hr_expense_portal/security/ir.model.access.csv
  hr_expense_portal/security/security.xml
  hr_expense_portal/static/description/icon.png
  hr_expense_portal/static/description/index.html
  hr_expense_portal/tests/__init__.py
  hr_expense_portal/tests/test_hr_expense_portal.py
  hr_expense_portal/views/expense_template.xml
  setup/hr_expense_portal/odoo/addons/hr_expense_portal
  setup/hr_expense_portal/setup.py
Labels: approved, ready to merge, bot is merging ⏳, hacktoberfest-accepted

#87 [FIX] hr_expense_advance_clearing: add context for clearing
  hr_expense_advance_clearing/models/hr_expense_sheet.py
Labels: approved, ready to merge, bot is merging ⏳

#97 [14.0][FIX] hr_expense_exception: show main exception on tree view
  hr_expense_exception/views/hr_expense_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#98 [14.0][FIX] hr_expense_advance_clearing: return advance - redirect payment message
  hr_expense_advance_clearing/wizard/account_payment_register.py
Labels: approved, bot is merging ⏳
