Repository OCA/hr-expense, pull requests merged in 2021-04, with the labels that each got.

#27 [14.0] [NEW] hr_expense_analytic_distribution: New module to distribute the expenses into various analytic account.
  hr_expense_analytic_distribution/README.rst
  hr_expense_analytic_distribution/__init__.py
  hr_expense_analytic_distribution/__manifest__.py
  hr_expense_analytic_distribution/models/__init__.py
  hr_expense_analytic_distribution/models/hr_expense.py
  hr_expense_analytic_distribution/models/hr_expense_distribution.py
  hr_expense_analytic_distribution/models/hr_expense_sheet.py
  hr_expense_analytic_distribution/readme/CONTRIBUTORS.rst
  hr_expense_analytic_distribution/readme/DESCRIPTION.rst
  hr_expense_analytic_distribution/readme/USAGE.rst
  hr_expense_analytic_distribution/security/ir.model.access.csv
  hr_expense_analytic_distribution/tests/__init__.py
  hr_expense_analytic_distribution/tests/test_expense.py
  hr_expense_analytic_distribution/views/hr_expense_distribution_views.xml
  hr_expense_analytic_distribution/views/hr_expense_sheet_views.xml
  setup/hr_expense_analytic_distribution/odoo/addons/hr_expense_analytic_distribution
  setup/hr_expense_analytic_distribution/setup.py
Labels: bot is merging ⏳

#34 [13.0][IMP+FIX] hr_expense_invoice: Add button to create invoice from expenses + Allow create invoice from invoice_id field
  hr_expense_invoice/models/account_move.py
  hr_expense_invoice/models/hr_expense.py
  hr_expense_invoice/tests/test_hr_expense_invoice.py
  hr_expense_invoice/views/hr_expense_views.xml
Labels: approved, bot is merging ⏳

#14 [14.0][MIG] hr_expense_cancel
  hr_expense_cancel/README.rst
  hr_expense_cancel/__init__.py
  hr_expense_cancel/__manifest__.py
  hr_expense_cancel/hooks.py
  hr_expense_cancel/i18n/es.po
  hr_expense_cancel/i18n/hr_expense_cancel.pot
  hr_expense_cancel/models/__init__.py
  hr_expense_cancel/models/account_payment.py
  hr_expense_cancel/models/hr_expense.py
  hr_expense_cancel/readme/CONTRIBUTORS.rst
  hr_expense_cancel/readme/DESCRIPTION.rst
  hr_expense_cancel/readme/INSTALL.rst
  hr_expense_cancel/readme/USAGE.rst
  hr_expense_cancel/static/description/icon.png
  hr_expense_cancel/static/description/index.html
  hr_expense_cancel/tests/__init__.py
  hr_expense_cancel/tests/test_hr_expense_cancel.py
  hr_expense_cancel/views/hr_expense_views.xml
  hr_expense_cancel/wizard/__init__.py
  hr_expense_cancel/wizard/account_payment_register.py
  setup/hr_expense_cancel/odoo/addons/hr_expense_cancel
  setup/hr_expense_cancel/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#30 [14.0][MIG] hr_expense_tier_validation
  hr_expense_tier_validation/README.rst
  hr_expense_tier_validation/__init__.py
  hr_expense_tier_validation/__manifest__.py
  hr_expense_tier_validation/i18n/hr_expense_tier_validation.pot
  hr_expense_tier_validation/models/__init__.py
  hr_expense_tier_validation/models/hr_expense_sheet.py
  hr_expense_tier_validation/models/tier_definition.py
  hr_expense_tier_validation/readme/CONFIGURE.rst
  hr_expense_tier_validation/readme/CONTRIBUTORS.rst
  hr_expense_tier_validation/readme/DESCRIPTION.rst
  hr_expense_tier_validation/readme/INSTALL.rst
  hr_expense_tier_validation/readme/USAGE.rst
  hr_expense_tier_validation/static/description/icon.png
  hr_expense_tier_validation/static/description/index.html
  hr_expense_tier_validation/tests/__init__.py
  hr_expense_tier_validation/tests/test_hr_expense_tier_validation.py
  hr_expense_tier_validation/views/hr_expense_sheet_view.xml
  setup/hr_expense_tier_validation/odoo/addons/hr_expense_tier_validation
  setup/hr_expense_tier_validation/setup.py
Labels: approved, bot is merging ⏳
