Repository OCA/hr-expense, pull requests merged in 2022-06, with the labels that each got.

#57 [14.0][ADD] hr_expense_payment_widget_amount
  hr_expense_payment_widget_amount/README.rst
  hr_expense_payment_widget_amount/__init__.py
  hr_expense_payment_widget_amount/__manifest__.py
  hr_expense_payment_widget_amount/models/__init__.py
  hr_expense_payment_widget_amount/models/account_move.py
  hr_expense_payment_widget_amount/models/hr_expense_sheet.py
  hr_expense_payment_widget_amount/readme/CONTRIBUTORS.rst
  hr_expense_payment_widget_amount/readme/DESCRIPTION.rst
  hr_expense_payment_widget_amount/static/description/icon.png
  hr_expense_payment_widget_amount/static/description/index.html
  hr_expense_payment_widget_amount/tests/__init__.py
  hr_expense_payment_widget_amount/tests/test_hr_expense_payment_widget_amount.py
  hr_expense_payment_widget_amount/views/hr_expense_views.xml
  setup/hr_expense_payment_widget_amount/odoo/addons/hr_expense_payment_widget_amount
  setup/hr_expense_payment_widget_amount/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#41 [14.0][MIG] hr_expense_advance_clearing_sequence
  hr_expense_advance_clearing_sequence/README.rst
  hr_expense_advance_clearing_sequence/__init__.py
  hr_expense_advance_clearing_sequence/__manifest__.py
  hr_expense_advance_clearing_sequence/data/hr_expense_data.xml
  hr_expense_advance_clearing_sequence/i18n/hr_expense_advance_clearing_sequence.pot
  hr_expense_advance_clearing_sequence/models/__init__.py
  hr_expense_advance_clearing_sequence/models/hr_expense_sheet.py
  hr_expense_advance_clearing_sequence/readme/CONFIGURE.rst
  hr_expense_advance_clearing_sequence/readme/CONTRIBUTORS.rst
  hr_expense_advance_clearing_sequence/readme/DESCRIPTION.rst
  hr_expense_advance_clearing_sequence/static/description/icon.png
  hr_expense_advance_clearing_sequence/static/description/index.html
  hr_expense_advance_clearing_sequence/tests/__init__.py
  hr_expense_advance_clearing_sequence/tests/test_hr_expense_advance_clearing_sequence.py
  setup/hr_expense_advance_clearing_sequence/odoo/addons/hr_expense_advance_clearing_sequence
  setup/hr_expense_advance_clearing_sequence/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#113 [14.0][FIX] hr_expense_payment: no create payments with paid by company
  hr_expense_cancel/tests/test_hr_expense_cancel.py
  hr_expense_payment/models/__init__.py
  hr_expense_payment/models/hr_expense.py
  hr_expense_payment/tests/test_hr_expense_payment.py
Labels: approved, bot is merging ⏳

#108 [14.0] Updated from template
  .copier-answers.yml
  .github/workflows/test.yml
  .travis.yml
  README.md
Labels: bot is merging ⏳

#107 [13.0] Update from template
  .copier-answers.yml
  .eslintrc.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  hr_expense_portal/__manifest__.py
Labels: bot is merging ⏳
