Repository OCA/hr-expense, pull requests merged in 2022-11, with the labels that each got.

#128 [15.0][MIG] hr_expense_exception
  hr_expense_exception/README.rst
  hr_expense_exception/__init__.py
  hr_expense_exception/__manifest__.py
  hr_expense_exception/data/expense_sheet_exception_data.xml
  hr_expense_exception/i18n/hr_expense_exception.pot
  hr_expense_exception/models/__init__.py
  hr_expense_exception/models/exception_rule.py
  hr_expense_exception/models/hr_expense.py
  hr_expense_exception/models/hr_expense_sheet.py
  hr_expense_exception/readme/CONTRIBUTORS.rst
  hr_expense_exception/readme/DESCRIPTION.rst
  hr_expense_exception/security/ir.model.access.csv
  hr_expense_exception/static/description/icon.png
  hr_expense_exception/static/description/index.html
  hr_expense_exception/tests/__init__.py
  hr_expense_exception/tests/test_expense_sheet_exception.py
  hr_expense_exception/views/hr_expense_view.xml
  hr_expense_exception/wizard/__init__.py
  hr_expense_exception/wizard/expense_sheet_exception_confirm.py
  hr_expense_exception/wizard/expense_sheet_exception_confirm_view.xml
  setup/hr_expense_exception/odoo/addons/hr_expense_exception
  setup/hr_expense_exception/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#130 [15.0] [MIG] hr_expense_portal
  hr_expense_portal/README.rst
  hr_expense_portal/__init__.py
  hr_expense_portal/__manifest__.py
  hr_expense_portal/controllers/__init__.py
  hr_expense_portal/controllers/expense_portal.py
  hr_expense_portal/i18n/hr_expense_portal.pot
  hr_expense_portal/readme/CONTRIBUTORS.rst
  hr_expense_portal/readme/CREDITS.rst
  hr_expense_portal/readme/DESCRIPTION.rst
  hr_expense_portal/security/ir.model.access.csv
  hr_expense_portal/security/security.xml
  hr_expense_portal/static/description/icon.png
  hr_expense_portal/static/description/index.html
  hr_expense_portal/tests/__init__.py
  hr_expense_portal/tests/test_hr_expense_portal.py
  hr_expense_portal/views/expense_template.xml
  setup/hr_expense_portal/odoo/addons/hr_expense_portal
  setup/hr_expense_portal/setup.py
Labels: bot is merging ⏳

#144 [15.0][FIX] hr_expense_invoice: Change SavepointCase to TransactionCase
  hr_expense_invoice/tests/test_hr_expense_invoice.py
Labels: bot is merging ⏳

#146 [14.0][FIX] hr_expense_sequence: Fix null value in column number, that violates not-null constraint
  hr_expense_sequence/models/hr_expense_sheet.py
Labels: approved, bot is merging ⏳

#82 [14.0][ADD] hr_expense_sheet_payment_state
  hr_expense_sheet_payment_state/README.rst
  hr_expense_sheet_payment_state/__init__.py
  hr_expense_sheet_payment_state/__manifest__.py
  hr_expense_sheet_payment_state/models/__init__.py
  hr_expense_sheet_payment_state/models/account_move.py
  hr_expense_sheet_payment_state/models/hr_expense.py
  hr_expense_sheet_payment_state/readme/CONTRIBUTORS.rst
  hr_expense_sheet_payment_state/readme/DESCRIPTION.rst
  hr_expense_sheet_payment_state/readme/USAGE.rst
  hr_expense_sheet_payment_state/static/description/icon.png
  hr_expense_sheet_payment_state/static/description/index.html
  hr_expense_sheet_payment_state/tests/__init__.py
  hr_expense_sheet_payment_state/tests/test_expense_sheet_payment_state.py
  hr_expense_sheet_payment_state/views/hr_expense_views.xml
  setup/hr_expense_sheet_payment_state/odoo/addons/hr_expense_sheet_payment_state
  setup/hr_expense_sheet_payment_state/setup.py
Labels: needs fixing, approved, ready to merge, bot is merging ⏳

#42 [14.0][ADD] hr_expense_work_acceptance
  hr_expense_work_acceptance/README.rst
  hr_expense_work_acceptance/__init__.py
  hr_expense_work_acceptance/__manifest__.py
  hr_expense_work_acceptance/models/__init__.py
  hr_expense_work_acceptance/models/hr_expense.py
  hr_expense_work_acceptance/models/res_config_settings.py
  hr_expense_work_acceptance/models/work_acceptance.py
  hr_expense_work_acceptance/readme/CONFIGURE.rst
  hr_expense_work_acceptance/readme/CONTRIBUTORS.rst
  hr_expense_work_acceptance/readme/DESCRIPTION.rst
  hr_expense_work_acceptance/readme/USAGE.rst
  hr_expense_work_acceptance/security/ir.model.access.csv
  hr_expense_work_acceptance/security/security.xml
  hr_expense_work_acceptance/static/description/icon.png
  hr_expense_work_acceptance/static/description/index.html
  hr_expense_work_acceptance/tests/__init__.py
  hr_expense_work_acceptance/tests/test_hr_expense_work_acceptance.py
  hr_expense_work_acceptance/views/expense_views.xml
  hr_expense_work_acceptance/views/res_config_settings_views.xml
  hr_expense_work_acceptance/views/work_acceptance_views.xml
  oca_dependencies.txt
  setup/hr_expense_work_acceptance/odoo/addons/hr_expense_work_acceptance
  setup/hr_expense_work_acceptance/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#142 [14.0][FIX] hr_expense_advance_clearing: allow general user to create clearing
  hr_expense_advance_clearing/views/hr_expense_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#156 16.0 [UPD] dotfiles
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: approved

#139 [15.0][MIG] hr_expense_sequence
  hr_expense_sequence/README.rst
  hr_expense_sequence/__init__.py
  hr_expense_sequence/__manifest__.py
  hr_expense_sequence/data/hr_expense_data.xml
  hr_expense_sequence/hooks.py
  hr_expense_sequence/i18n/cs_CZ.po
  hr_expense_sequence/i18n/de.po
  hr_expense_sequence/i18n/es.po
  hr_expense_sequence/i18n/fi.po
  hr_expense_sequence/i18n/fr.po
  hr_expense_sequence/i18n/hr.po
  hr_expense_sequence/i18n/hr_expense_sequence.pot
  hr_expense_sequence/i18n/it.po
  hr_expense_sequence/i18n/nl_NL.po
  hr_expense_sequence/i18n/pt_BR.po
  hr_expense_sequence/i18n/sl.po
  hr_expense_sequence/models/__init__.py
  hr_expense_sequence/models/hr_expense_sheet.py
  hr_expense_sequence/readme/CONFIGURE.rst
  hr_expense_sequence/readme/CONTRIBUTORS.rst
  hr_expense_sequence/readme/DESCRIPTION.rst
  hr_expense_sequence/report/report_expense_sheet.xml
  hr_expense_sequence/static/description/icon.png
  hr_expense_sequence/static/description/index.html
  hr_expense_sequence/tests/__init__.py
  hr_expense_sequence/tests/test_hr_expense_sequence.py
  hr_expense_sequence/views/hr_expense_expense_view.xml
  setup/hr_expense_sequence/odoo/addons/hr_expense_sequence
  setup/hr_expense_sequence/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#152 [15.0][FIX] hr_expense_advance_clearing: allow general user to create clearing
  hr_expense_advance_clearing/views/hr_expense_views.xml
Labels: approved, ready to merge, bot is merging ⏳
