Repository OCA/hr-expense, pull requests merged in 2022-04, with the labels that each got.

#100 [MIG] hr_expense_invoice: Migration to 15.0
  hr_expense_invoice/README.rst
  hr_expense_invoice/__init__.py
  hr_expense_invoice/__manifest__.py
  hr_expense_invoice/i18n/cs_CZ.po
  hr_expense_invoice/i18n/de.po
  hr_expense_invoice/i18n/es.po
  hr_expense_invoice/i18n/fr.po
  hr_expense_invoice/i18n/hr.po
  hr_expense_invoice/i18n/hr_expense_invoice.pot
  hr_expense_invoice/i18n/nl_NL.po
  hr_expense_invoice/i18n/pt.po
  hr_expense_invoice/models/__init__.py
  hr_expense_invoice/models/account_move.py
  hr_expense_invoice/models/hr_expense.py
  hr_expense_invoice/models/hr_expense_sheet.py
  hr_expense_invoice/readme/CONTRIBUTORS.rst
  hr_expense_invoice/readme/DESCRIPTION.rst
  hr_expense_invoice/readme/ROADMAP.rst
  hr_expense_invoice/readme/USAGE.rst
  hr_expense_invoice/static/description/icon.png
  hr_expense_invoice/static/description/index.html
  hr_expense_invoice/tests/__init__.py
  hr_expense_invoice/tests/test_hr_expense_invoice.py
  hr_expense_invoice/views/hr_expense_views.xml
  hr_expense_invoice/wizard/__init__.py
  hr_expense_invoice/wizard/account_payment_register.py
  setup/hr_expense_invoice/odoo/addons/hr_expense_invoice
  setup/hr_expense_invoice/setup.py
Labels: bot is merging ⏳

#111 [15.0][FIX]sale_expense_manual_reinvoice: post_install at_install test tags
  sale_expense_manual_reinvoice/tests/test_sale_expense_manual_reinvoice.py
Labels: bot is merging ⏳

#110 [15.0][MIG]hr_expense_payment
  hr_expense_payment/README.rst
  hr_expense_payment/__init__.py
  hr_expense_payment/__manifest__.py
  hr_expense_payment/hooks.py
  hr_expense_payment/i18n/hr_expense_payment.pot
  hr_expense_payment/models/__init__.py
  hr_expense_payment/models/account_payment.py
  hr_expense_payment/models/hr_expense.py
  hr_expense_payment/models/hr_expense_sheet.py
  hr_expense_payment/readme/CONTRIBUTORS.rst
  hr_expense_payment/readme/DESCRIPTION.rst
  hr_expense_payment/static/description/icon.png
  hr_expense_payment/static/description/index.html
  hr_expense_payment/tests/__init__.py
  hr_expense_payment/tests/test_hr_expense_payment.py
  hr_expense_payment/wizard/__init__.py
  hr_expense_payment/wizard/account_payment_register.py
  setup/hr_expense_payment/odoo/addons/hr_expense_payment
  setup/hr_expense_payment/setup.py
Labels: approved, bot is merging ⏳

#66 [14.0][MIG] hr_expense_petty_cash
  hr_expense_petty_cash/README.rst
  hr_expense_petty_cash/__init__.py
  hr_expense_petty_cash/__manifest__.py
  hr_expense_petty_cash/i18n/hr_expense_petty_cash.pot
  hr_expense_petty_cash/models/__init__.py
  hr_expense_petty_cash/models/account_move.py
  hr_expense_petty_cash/models/hr_expense.py
  hr_expense_petty_cash/models/hr_expense_sheet.py
  hr_expense_petty_cash/models/petty_cash.py
  hr_expense_petty_cash/readme/CONFIGURE.rst
  hr_expense_petty_cash/readme/CONTRIBUTORS.rst
  hr_expense_petty_cash/readme/DESCRIPTION.rst
  hr_expense_petty_cash/readme/USAGE.rst
  hr_expense_petty_cash/security/ir.model.access.csv
  hr_expense_petty_cash/static/description/icon.png
  hr_expense_petty_cash/static/description/index.html
  hr_expense_petty_cash/tests/__init__.py
  hr_expense_petty_cash/tests/test_hr_expense_petty_cash.py
  hr_expense_petty_cash/views/account_move_views.xml
  hr_expense_petty_cash/views/hr_expense_sheet_views.xml
  hr_expense_petty_cash/views/hr_expense_views.xml
  hr_expense_petty_cash/views/petty_cash_views.xml
  setup/hr_expense_petty_cash/odoo/addons/hr_expense_petty_cash
  setup/hr_expense_petty_cash/setup.py
Labels: approved, ready to merge, bot is merging ⏳
