Repository OCA/hr-expense, pull requests merged in 2022-10, with the labels that each got.

#104 [14.0][FIX] hr_expense_advance_clearing: do not allow cancel PV related clearing or return
  hr_expense_advance_clearing/models/__init__.py
  hr_expense_advance_clearing/models/account_move.py
  hr_expense_advance_clearing/models/hr_expense.py
Labels: approved, bot is merging ⏳, stale

#119 [14.0][ENH] hr_expense_advance_clearing, not allow over return
  hr_expense_advance_clearing/models/hr_expense_sheet.py
  hr_expense_advance_clearing/wizard/account_payment_register.py
Labels: approved, bot is merging ⏳

#53 [14.0][ADD] hr_expense_widget_o2m
  hr_expense_widget_o2m/__init__.py
  hr_expense_widget_o2m/__manifest__.py
  hr_expense_widget_o2m/models/__init__.py
  hr_expense_widget_o2m/models/res_config_settings.py
  hr_expense_widget_o2m/readme/CONFIGURE.rst
  hr_expense_widget_o2m/readme/CONTRIBUTORS.rst
  hr_expense_widget_o2m/readme/DESCRIPTION.rst
  hr_expense_widget_o2m/security/hr_expense_security.xml
  hr_expense_widget_o2m/static/description/icon.png
  hr_expense_widget_o2m/views/hr_expense_views.xml
  hr_expense_widget_o2m/views/res_config_settings_views.xml
  setup/hr_expense_widget_o2m/odoo/addons/hr_expense_widget_o2m
  setup/hr_expense_widget_o2m/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#93 [14.0][ADD] hr_expense_substate
  hr_expense_substate/README.rst
  hr_expense_substate/__init__.py
  hr_expense_substate/__manifest__.py
  hr_expense_substate/data/hr_expense_substate_data.xml
  hr_expense_substate/data/hr_expense_substate_mail_template_data.xml
  hr_expense_substate/demo/hr_expense_substate_demo.xml
  hr_expense_substate/models/__init__.py
  hr_expense_substate/models/hr_expense.py
  hr_expense_substate/readme/CONTRIBUTORS.rst
  hr_expense_substate/readme/DESCRIPTION.rst
  hr_expense_substate/readme/USAGE.rst
  hr_expense_substate/static/description/icon.png
  hr_expense_substate/static/description/index.html
  hr_expense_substate/views/hr_expense_views.xml
  oca_dependencies.txt
  setup/hr_expense_substate/odoo/addons/hr_expense_substate
  setup/hr_expense_substate/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#61 [14.0][ADD] hr_expense_pay_to_vendor
  hr_expense_pay_to_vendor/__init__.py
  hr_expense_pay_to_vendor/__manifest__.py
  hr_expense_pay_to_vendor/models/__init__.py
  hr_expense_pay_to_vendor/models/hr_expense.py
  hr_expense_pay_to_vendor/readme/CONTRIBUTORS.rst
  hr_expense_pay_to_vendor/readme/DESCRIPTION.rst
  hr_expense_pay_to_vendor/readme/USAGE.rst
  hr_expense_pay_to_vendor/static/description/icon.png
  hr_expense_pay_to_vendor/tests/__init__.py
  hr_expense_pay_to_vendor/tests/test_hr_expense_pay_to_vendor.py
  hr_expense_pay_to_vendor/views/hr_expense_views.xml
  setup/hr_expense_pay_to_vendor/odoo/addons/hr_expense_pay_to_vendor
  setup/hr_expense_pay_to_vendor/setup.py
Labels: bot is merging ⏳, stale

#133 [13.0][IMP] hr_expense_invoice: Change _validate_expense_invoice() function to use amount_total from invoices.
  hr_expense_invoice/models/hr_expense_sheet.py
Labels: approved, bot is merging ⏳

#120 [14.0][FIX] hr_expense_tier_validation: disallow editable expense from the expense report is under validation
  hr_expense_tier_validation/models/__init__.py
  hr_expense_tier_validation/models/hr_expense.py
  hr_expense_tier_validation/tests/test_hr_expense_tier_validation.py
Labels: approved, ready to merge, bot is merging ⏳

#135 [15.0][IMP] hr_expense_invoice: Change _validate_expense_invoice() function to use amount_total from invoices.
  hr_expense_invoice/models/hr_expense_sheet.py
Labels: approved, bot is merging ⏳

#137 [FIX] hr_expense_substate: reference wrong external id
  hr_expense_substate/demo/hr_expense_substate_demo.xml
Labels: bot is merging ⏳

#103 [15.0][MIG] hr_expense_advance_clearing
  hr_expense_advance_clearing/README.rst
  hr_expense_advance_clearing/__init__.py
  hr_expense_advance_clearing/__manifest__.py
  hr_expense_advance_clearing/data/advance_product.xml
  hr_expense_advance_clearing/i18n/hr_expense_advance_clearing.pot
  hr_expense_advance_clearing/models/__init__.py
  hr_expense_advance_clearing/models/account_move.py
  hr_expense_advance_clearing/models/account_payment.py
  hr_expense_advance_clearing/models/hr_employee_base.py
  hr_expense_advance_clearing/models/hr_expense.py
  hr_expense_advance_clearing/models/hr_expense_sheet.py
  hr_expense_advance_clearing/readme/CONFIGURE.rst
  hr_expense_advance_clearing/readme/CONTRIBUTORS.rst
  hr_expense_advance_clearing/readme/DESCRIPTION.rst
  hr_expense_advance_clearing/readme/USAGE.rst
  hr_expense_advance_clearing/static/description/icon.png
  hr_expense_advance_clearing/static/description/index.html
  hr_expense_advance_clearing/tests/__init__.py
  hr_expense_advance_clearing/tests/test_hr_expense_advance_clearing.py
  hr_expense_advance_clearing/views/account_payment_view.xml
  hr_expense_advance_clearing/views/hr_employee_public_views.xml
  hr_expense_advance_clearing/views/hr_employee_views.xml
  hr_expense_advance_clearing/views/hr_expense_views.xml
  hr_expense_advance_clearing/wizard/__init__.py
  hr_expense_advance_clearing/wizard/account_payment_register.py
  setup/hr_expense_advance_clearing/odoo/addons/hr_expense_advance_clearing
  setup/hr_expense_advance_clearing/setup.py
Labels: approved, ready to merge, bot is merging ⏳
