Repository OCA/hr-expense, pull requests merged in 2023-11, with the labels that each got.

#168 [15.0][ADD] hr_expense_cancel_confirm
  hr_expense_cancel_confirm/README.rst
  hr_expense_cancel_confirm/__init__.py
  hr_expense_cancel_confirm/__manifest__.py
  hr_expense_cancel_confirm/data/config_parameter.xml
  hr_expense_cancel_confirm/model/__init__.py
  hr_expense_cancel_confirm/model/hr_expense.py
  hr_expense_cancel_confirm/readme/CONFIGURE.rst
  hr_expense_cancel_confirm/readme/CONTRIBUTORS.rst
  hr_expense_cancel_confirm/readme/DESCRIPTION.rst
  hr_expense_cancel_confirm/static/description/icon.png
  hr_expense_cancel_confirm/static/description/index.html
  hr_expense_cancel_confirm/tests/__init__.py
  hr_expense_cancel_confirm/tests/test_hr_expense_cancel_confirm.py
  hr_expense_cancel_confirm/wizard/__init__.py
  hr_expense_cancel_confirm/wizard/cancel_confirm.py
  setup/hr_expense_cancel_confirm/odoo/addons/hr_expense_cancel_confirm
  setup/hr_expense_cancel_confirm/setup.py
Labels: approved, bot is merging ⏳

#213 [16.0][MIG] hr_expense_sequence
  hr_expense_sequence/README.rst
  hr_expense_sequence/__init__.py
  hr_expense_sequence/__manifest__.py
  hr_expense_sequence/data/hr_expense_data.xml
  hr_expense_sequence/hooks.py
  hr_expense_sequence/i18n/cs_CZ.po
  hr_expense_sequence/i18n/de.po
  hr_expense_sequence/i18n/es.po
  hr_expense_sequence/i18n/fi.po
  hr_expense_sequence/i18n/fr.po
  hr_expense_sequence/i18n/hr.po
  hr_expense_sequence/i18n/hr_expense_sequence.pot
  hr_expense_sequence/i18n/it.po
  hr_expense_sequence/i18n/nl_NL.po
  hr_expense_sequence/i18n/pt_BR.po
  hr_expense_sequence/i18n/sl.po
  hr_expense_sequence/models/__init__.py
  hr_expense_sequence/models/hr_expense_sheet.py
  hr_expense_sequence/readme/CONFIGURE.rst
  hr_expense_sequence/readme/CONTRIBUTORS.rst
  hr_expense_sequence/readme/DESCRIPTION.rst
  hr_expense_sequence/report/report_expense_sheet.xml
  hr_expense_sequence/static/description/icon.png
  hr_expense_sequence/static/description/index.html
  hr_expense_sequence/tests/__init__.py
  hr_expense_sequence/tests/test_hr_expense_sequence.py
  hr_expense_sequence/views/hr_expense_expense_view.xml
  setup/hr_expense_sequence/odoo/addons/hr_expense_sequence
  setup/hr_expense_sequence/setup.py
Labels: approved, bot is merging ⏳

#209 [16.0][MIG] hr_expense_tier_validation
  hr_expense_tier_validation/README.rst
  hr_expense_tier_validation/__init__.py
  hr_expense_tier_validation/__manifest__.py
  hr_expense_tier_validation/i18n/hr_expense_tier_validation.pot
  hr_expense_tier_validation/i18n/it.po
  hr_expense_tier_validation/models/__init__.py
  hr_expense_tier_validation/models/hr_expense.py
  hr_expense_tier_validation/models/hr_expense_sheet.py
  hr_expense_tier_validation/models/tier_definition.py
  hr_expense_tier_validation/readme/CONFIGURE.rst
  hr_expense_tier_validation/readme/CONTRIBUTORS.rst
  hr_expense_tier_validation/readme/DESCRIPTION.rst
  hr_expense_tier_validation/readme/INSTALL.rst
  hr_expense_tier_validation/readme/USAGE.rst
  hr_expense_tier_validation/static/description/icon.png
  hr_expense_tier_validation/static/description/index.html
  hr_expense_tier_validation/tests/__init__.py
  hr_expense_tier_validation/tests/test_hr_expense_tier_validation.py
  hr_expense_tier_validation/views/hr_expense_sheet_view.xml
  setup/hr_expense_tier_validation/odoo/addons/hr_expense_tier_validation
  setup/hr_expense_tier_validation/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#163 [15.0][ADD] hr_expense_excluded_tax
  hr_expense_excluded_tax/README.rst
  hr_expense_excluded_tax/__init__.py
  hr_expense_excluded_tax/__manifest__.py
  hr_expense_excluded_tax/models/__init__.py
  hr_expense_excluded_tax/models/hr_expense.py
  hr_expense_excluded_tax/readme/CONTRIBUTORS.rst
  hr_expense_excluded_tax/readme/DESCRIPTION.rst
  hr_expense_excluded_tax/static/description/icon.png
  hr_expense_excluded_tax/static/description/index.html
  hr_expense_excluded_tax/tests/__init__.py
  hr_expense_excluded_tax/tests/test_hr_expense_excluded_tax.py
  hr_expense_excluded_tax/views/hr_expense_views.xml
  setup/hr_expense_excluded_tax/odoo/addons/hr_expense_excluded_tax
  setup/hr_expense_excluded_tax/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#203 [16.0][MIG] hr_expense_advance_clearing
  hr_expense_advance_clearing/README.rst
  hr_expense_advance_clearing/__init__.py
  hr_expense_advance_clearing/__manifest__.py
  hr_expense_advance_clearing/data/advance_product.xml
  hr_expense_advance_clearing/i18n/hr_expense_advance_clearing.pot
  hr_expense_advance_clearing/i18n/it.po
  hr_expense_advance_clearing/models/__init__.py
  hr_expense_advance_clearing/models/account_move.py
  hr_expense_advance_clearing/models/account_payment.py
  hr_expense_advance_clearing/models/hr_employee_base.py
  hr_expense_advance_clearing/models/hr_expense.py
  hr_expense_advance_clearing/models/hr_expense_sheet.py
  hr_expense_advance_clearing/readme/CONFIGURE.rst
  hr_expense_advance_clearing/readme/CONTRIBUTORS.rst
  hr_expense_advance_clearing/readme/DESCRIPTION.rst
  hr_expense_advance_clearing/readme/USAGE.rst
  hr_expense_advance_clearing/static/description/icon.png
  hr_expense_advance_clearing/static/description/index.html
  hr_expense_advance_clearing/tests/__init__.py
  hr_expense_advance_clearing/tests/test_hr_expense_advance_clearing.py
  hr_expense_advance_clearing/views/account_payment_view.xml
  hr_expense_advance_clearing/views/hr_employee_public_views.xml
  hr_expense_advance_clearing/views/hr_employee_views.xml
  hr_expense_advance_clearing/views/hr_expense_views.xml
  hr_expense_advance_clearing/wizard/__init__.py
  hr_expense_advance_clearing/wizard/account_payment_register.py
  setup/hr_expense_advance_clearing/odoo/addons/hr_expense_advance_clearing
  setup/hr_expense_advance_clearing/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#190 [15.0][FIX] hr_expense_petty_cash: add permission for internal user
  hr_expense_petty_cash/models/petty_cash.py
  hr_expense_petty_cash/security/ir.model.access.csv
Labels: bot is merging ⏳
