Repository OCA/hr-expense, pull requests merged in 2023-10, with the labels that each got.

#182 [15.0][ADD] hr_expense_advance_overdue_reminder
  hr_expense_advance_overdue_reminder/README.rst
  hr_expense_advance_overdue_reminder/__init__.py
  hr_expense_advance_overdue_reminder/__manifest__.py
  hr_expense_advance_overdue_reminder/data/mail_template.xml
  hr_expense_advance_overdue_reminder/data/sequence_data.xml
  hr_expense_advance_overdue_reminder/models/__init__.py
  hr_expense_advance_overdue_reminder/models/base_reminder_mixin.py
  hr_expense_advance_overdue_reminder/models/hr_advance_overdue_reminder.py
  hr_expense_advance_overdue_reminder/models/hr_expense_sheet.py
  hr_expense_advance_overdue_reminder/models/reminder_definition.py
  hr_expense_advance_overdue_reminder/readme/CONFIGURE.rst
  hr_expense_advance_overdue_reminder/readme/CONTRIBUTORS.rst
  hr_expense_advance_overdue_reminder/readme/DESCRIPTION.rst
  hr_expense_advance_overdue_reminder/readme/USAGE.rst
  hr_expense_advance_overdue_reminder/security/ir.model.access.csv
  hr_expense_advance_overdue_reminder/static/description/index.html
  hr_expense_advance_overdue_reminder/tests/__init__.py
  hr_expense_advance_overdue_reminder/tests/test_hr_expense_advance_overdue_reminder.py
  hr_expense_advance_overdue_reminder/views/hr_advance_overdue_view.xml
  hr_expense_advance_overdue_reminder/views/hr_expense_views.xml
  hr_expense_advance_overdue_reminder/views/reminder_definition_view.xml
  hr_expense_advance_overdue_reminder/wizard/__init__.py
  hr_expense_advance_overdue_reminder/wizard/hr_advance_overdue_reminder_wizard.py
  hr_expense_advance_overdue_reminder/wizard/hr_advance_overdue_reminder_wizard.xml
  hr_expense_advance_overdue_reminder/wizard/mail_compose_message.py
  setup/hr_expense_advance_overdue_reminder/odoo/addons/hr_expense_advance_overdue_reminder
  setup/hr_expense_advance_overdue_reminder/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#207 [16.0][ADD] hr_expense_analytic_tag: New module
  hr_expense_analytic_tag/README.rst
  hr_expense_analytic_tag/__init__.py
  hr_expense_analytic_tag/__manifest__.py
  hr_expense_analytic_tag/i18n/es.po
  hr_expense_analytic_tag/i18n/hr_expense_analytic_tag.pot
  hr_expense_analytic_tag/models/__init__.py
  hr_expense_analytic_tag/models/hr_expense.py
  hr_expense_analytic_tag/readme/CONTRIBUTORS.rst
  hr_expense_analytic_tag/readme/DESCRIPTION.rst
  hr_expense_analytic_tag/static/description/icon.png
  hr_expense_analytic_tag/static/description/index.html
  hr_expense_analytic_tag/tests/__init__.py
  hr_expense_analytic_tag/tests/test_hr_expense_analytic_tag.py
  hr_expense_analytic_tag/views/hr_expense_view.xml
  setup/hr_expense_analytic_tag/odoo/addons/hr_expense_analytic_tag
  setup/hr_expense_analytic_tag/setup.py
Labels: approved, bot is merging ⏳

#208 [16.0][REM] hr_expense_analytic_tag: Moved to OCA/account-analytic
  hr_expense_analytic_tag/README.rst
  hr_expense_analytic_tag/__init__.py
  hr_expense_analytic_tag/__manifest__.py
  hr_expense_analytic_tag/i18n/es.po
  hr_expense_analytic_tag/i18n/hr_expense_analytic_tag.pot
  hr_expense_analytic_tag/models/__init__.py
  hr_expense_analytic_tag/models/hr_expense.py
  hr_expense_analytic_tag/readme/CONTRIBUTORS.rst
  hr_expense_analytic_tag/readme/DESCRIPTION.rst
  hr_expense_analytic_tag/static/description/icon.png
  hr_expense_analytic_tag/static/description/index.html
  hr_expense_analytic_tag/tests/__init__.py
  hr_expense_analytic_tag/tests/test_hr_expense_analytic_tag.py
  hr_expense_analytic_tag/views/hr_expense_view.xml
  setup/hr_expense_analytic_tag/odoo/addons/hr_expense_analytic_tag
  setup/hr_expense_analytic_tag/setup.py
Labels: bot is merging ⏳

#180 [15.0][MIG] hr_expense_journal
  hr_expense_journal/README.rst
  hr_expense_journal/__init__.py
  hr_expense_journal/__manifest__.py
  hr_expense_journal/i18n/hr_expense_journal.pot
  hr_expense_journal/models/__init__.py
  hr_expense_journal/models/hr_expense.py
  hr_expense_journal/readme/CONTRIBUTORS.rst
  hr_expense_journal/readme/DESCRIPTION.rst
  hr_expense_journal/readme/USAGE.rst
  hr_expense_journal/static/description/icon.png
  hr_expense_journal/static/description/index.html
  hr_expense_journal/tests/__init__.py
  hr_expense_journal/tests/test_hr_expense_journal.py
  hr_expense_journal/views/hr_expense_views.xml
  setup/hr_expense_journal/odoo/addons/hr_expense_journal
  setup/hr_expense_journal/setup.py
Labels: approved, bot is merging ⏳

#176 [15.0][FIX] hr_expense_advance_clearing: split function return advance and check advance residual
  hr_expense_advance_clearing/models/hr_expense.py
  hr_expense_advance_clearing/models/hr_expense_sheet.py
  hr_expense_advance_clearing/tests/test_hr_expense_advance_clearing.py
  hr_expense_advance_clearing/wizard/account_payment_register.py
Labels: approved, ready to merge, bot is merging ⏳

#211 [15.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  hr_expense_advance_clearing/i18n/hr_expense_advance_clearing.pot
  hr_expense_advance_clearing/wizard/account_payment_register.py
  hr_expense_advance_overdue_reminder/i18n/hr_expense_advance_overdue_reminder.pot
Labels: help wanted, needs review
