Repository OCA/hr-expense, pull requests merged in 2023-04, with the labels that each got.

#161 [FIX][14.0] hr_expense_invoice default_move_type to show vendor
  hr_expense_invoice/views/hr_expense_views.xml
Labels: approved, bot is merging ⏳

#172 [15.0][ADD] hr_expense_tax_adjust
  hr_expense_tax_adjust/README.rst
  hr_expense_tax_adjust/__init__.py
  hr_expense_tax_adjust/__manifest__.py
  hr_expense_tax_adjust/models/__init__.py
  hr_expense_tax_adjust/models/hr_expense.py
  hr_expense_tax_adjust/readme/CONTRIBUTORS.rst
  hr_expense_tax_adjust/readme/DESCRIPTION.rst
  hr_expense_tax_adjust/readme/USAGE.rst
  hr_expense_tax_adjust/static/description/icon.png
  hr_expense_tax_adjust/static/description/index.html
  hr_expense_tax_adjust/tests/__init__.py
  hr_expense_tax_adjust/tests/test_hr_expense_tax_adjust.py
  hr_expense_tax_adjust/views/hr_expense_views.xml
  setup/hr_expense_tax_adjust/odoo/addons/hr_expense_tax_adjust
  setup/hr_expense_tax_adjust/setup.py
Labels: approved, bot is merging ⏳

#174 [15.0][FIX] hr_expense_advance_clearing: change field not compute advance
  hr_expense_advance_clearing/models/hr_expense_sheet.py
  hr_expense_advance_clearing/tests/test_hr_expense_advance_clearing.py
  hr_expense_advance_clearing/views/hr_expense_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#171 [15.0][FIX] hr_expense_advance_clearing: update readme
  hr_expense_advance_clearing/README.rst
  hr_expense_advance_clearing/readme/USAGE.rst
  hr_expense_advance_clearing/static/description/index.html
Labels: bot is merging ⏳
