Repository OCA/hr-expense, pull requests merged in 2024-05, with the labels that each got.

#149 [15.0][MIG] hr_expense_sequence_option
  hr_expense_sequence_option/README.rst
  hr_expense_sequence_option/__init__.py
  hr_expense_sequence_option/__manifest__.py
  hr_expense_sequence_option/demo/hr_expense_demo_options.xml
  hr_expense_sequence_option/i18n/hr_expense_sequence_option.pot
  hr_expense_sequence_option/models/__init__.py
  hr_expense_sequence_option/models/hr_expense_sheet.py
  hr_expense_sequence_option/models/sequence_option.py
  hr_expense_sequence_option/readme/CONTRIBUTORS.rst
  hr_expense_sequence_option/readme/DESCRIPTION.rst
  hr_expense_sequence_option/static/description/icon.png
  hr_expense_sequence_option/static/description/index.html
  hr_expense_sequence_option/tests/__init__.py
  hr_expense_sequence_option/tests/test_hr_expense_sequence_option.py
  setup/hr_expense_sequence_option/odoo/addons/hr_expense_sequence_option
  setup/hr_expense_sequence_option/setup.py
Labels: bot is merging ⏳

#196 [15.0][FIX] hr_expense_payment_widget_amount: back state to posted when unreconcile payment
  hr_expense_payment_widget_amount/models/account_move.py
Labels: bot is merging ⏳

#212 [15.0][FIX] hr_expense_tax_adjust: rounding diff price tax
  hr_expense_tax_adjust/models/hr_expense.py
Labels: bot is merging ⏳, stale

#236 [16.0][FIX] hr_expense_tier_validation: tests failing
  hr_expense_tier_validation/tests/test_hr_expense_tier_validation.py
Labels: bot is merging ⏳

#229 [17.0][MIG] hr_expense_payment: Migration to 17.0
  hr_expense_payment/README.rst
  hr_expense_payment/__init__.py
  hr_expense_payment/__manifest__.py
  hr_expense_payment/hooks.py
  hr_expense_payment/i18n/hr_expense_payment.pot
  hr_expense_payment/i18n/it.po
  hr_expense_payment/models/__init__.py
  hr_expense_payment/models/account_payment.py
  hr_expense_payment/models/hr_expense_sheet.py
  hr_expense_payment/pyproject.toml
  hr_expense_payment/readme/CONTRIBUTORS.md
  hr_expense_payment/readme/DESCRIPTION.md
  hr_expense_payment/static/description/icon.png
  hr_expense_payment/static/description/index.html
  hr_expense_payment/tests/__init__.py
  hr_expense_payment/tests/test_hr_expense_payment.py
  hr_expense_payment/wizard/__init__.py
  hr_expense_payment/wizard/account_payment_register.py
Labels: approved, ready to merge, bot is merging ⏳
