Repository OCA/hr-expense, pull requests merged in 2024-09, with the labels that each got.

#240 [16.0][MIG] hr_expense_advance_clearing_sequence
  hr_expense_advance_clearing_sequence/README.rst
  hr_expense_advance_clearing_sequence/__init__.py
  hr_expense_advance_clearing_sequence/__manifest__.py
  hr_expense_advance_clearing_sequence/data/hr_expense_data.xml
  hr_expense_advance_clearing_sequence/i18n/hr_expense_advance_clearing_sequence.pot
  hr_expense_advance_clearing_sequence/i18n/it.po
  hr_expense_advance_clearing_sequence/models/__init__.py
  hr_expense_advance_clearing_sequence/models/hr_expense_sheet.py
  hr_expense_advance_clearing_sequence/readme/CONFIGURE.rst
  hr_expense_advance_clearing_sequence/readme/CONTRIBUTORS.rst
  hr_expense_advance_clearing_sequence/readme/DESCRIPTION.rst
  hr_expense_advance_clearing_sequence/static/description/icon.png
  hr_expense_advance_clearing_sequence/static/description/index.html
  hr_expense_advance_clearing_sequence/tests/__init__.py
  hr_expense_advance_clearing_sequence/tests/test_hr_expense_advance_clearing_sequence.py
  setup/hr_expense_advance_clearing_sequence/odoo/addons/hr_expense_advance_clearing_sequence
  setup/hr_expense_advance_clearing_sequence/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#262 [14.0][ADD] hr_expense_due_date: new module
  hr_expense_due_date/README.rst
  hr_expense_due_date/__init__.py
  hr_expense_due_date/__manifest__.py
  hr_expense_due_date/models/__init__.py
  hr_expense_due_date/models/hr_expense.py
  hr_expense_due_date/models/hr_expense_sheet.py
  hr_expense_due_date/readme/CONTRIBUTORS.rst
  hr_expense_due_date/readme/DESCRIPTION.rst
  hr_expense_due_date/readme/USAGE.rst
  hr_expense_due_date/static/description/icon.png
  hr_expense_due_date/static/description/index.html
  hr_expense_due_date/tests/__init__.py
  hr_expense_due_date/tests/test_hr_expense_sheet.py
  hr_expense_due_date/views/hr_expense_sheet.xml
  setup/hr_expense_due_date/odoo/addons/hr_expense_due_date
  setup/hr_expense_due_date/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#256 [17.0][MIG] hr_expense_invoice: Migration to 17.0
  hr_expense_invoice/README.rst
  hr_expense_invoice/__init__.py
  hr_expense_invoice/__manifest__.py
  hr_expense_invoice/i18n/cs_CZ.po
  hr_expense_invoice/i18n/de.po
  hr_expense_invoice/i18n/es.po
  hr_expense_invoice/i18n/fr.po
  hr_expense_invoice/i18n/hr.po
  hr_expense_invoice/i18n/hr_expense_invoice.pot
  hr_expense_invoice/i18n/it.po
  hr_expense_invoice/i18n/nl_NL.po
  hr_expense_invoice/i18n/pt.po
  hr_expense_invoice/models/__init__.py
  hr_expense_invoice/models/account_move.py
  hr_expense_invoice/models/hr_expense.py
  hr_expense_invoice/models/hr_expense_sheet.py
  hr_expense_invoice/pyproject.toml
  hr_expense_invoice/readme/CONTRIBUTORS.md
  hr_expense_invoice/readme/DESCRIPTION.md
  hr_expense_invoice/readme/ROADMAP.md
  hr_expense_invoice/readme/USAGE.md
  hr_expense_invoice/static/description/icon.png
  hr_expense_invoice/static/description/index.html
  hr_expense_invoice/tests/__init__.py
  hr_expense_invoice/tests/test_hr_expense_invoice.py
  hr_expense_invoice/views/account_move_views.xml
  hr_expense_invoice/views/hr_expense_views.xml
Labels: approved, bot is merging ⏳

#249 [16.0][FIX] hr_expense_invoice: Incorrect data and check when creating vendor bill from expense
  hr_expense_invoice/models/account_move.py
  hr_expense_invoice/models/hr_expense.py
Labels: bot is merging ⏳

#268 [FIX] [16.0] hr_expense_invoice: Decide when to check expense amount
  hr_expense_invoice/models/account_move.py
Labels: approved, bot is merging ⏳
