Repository OCA/hr-expense, pull requests merged in 2024-11, with the labels that each got.

#96 [14.0][ADD] hr_expense_tax_adjust
  hr_expense_tax_adjust/README.rst
  hr_expense_tax_adjust/__init__.py
  hr_expense_tax_adjust/__manifest__.py
  hr_expense_tax_adjust/models/__init__.py
  hr_expense_tax_adjust/models/hr_expense.py
  hr_expense_tax_adjust/readme/CONTRIBUTORS.rst
  hr_expense_tax_adjust/readme/DESCRIPTION.rst
  hr_expense_tax_adjust/static/description/icon.png
  hr_expense_tax_adjust/static/description/index.html
  hr_expense_tax_adjust/static/src/js/tax_group.js
  hr_expense_tax_adjust/static/src/xml/tax_group.xml
  hr_expense_tax_adjust/views/asset_backend.xml
  hr_expense_tax_adjust/views/hr_expense_views.xml
  setup/hr_expense_tax_adjust/odoo/addons/hr_expense_tax_adjust
  setup/hr_expense_tax_adjust/setup.py
Labels: approved, bot is merging ⏳

#242 [15.0][ENH] hr_expense_petty_cash: multi-company
  hr_expense_petty_cash/__manifest__.py
  hr_expense_petty_cash/models/account_move.py
  hr_expense_petty_cash/models/hr_expense.py
  hr_expense_petty_cash/models/petty_cash.py
  hr_expense_petty_cash/security/petty_cash_security.xml
  hr_expense_petty_cash/static/description/index.html
  hr_expense_petty_cash/views/petty_cash_views.xml
Labels: approved, bot is merging ⏳

#278 [16.0][FIX] hr_expense_*: Fix + improve tests
  hr_expense_advance_clearing/tests/test_hr_expense_advance_clearing.py
  hr_expense_cancel/tests/test_hr_expense_cancel.py
  hr_expense_invoice/tests/test_hr_expense_invoice.py
  hr_expense_payment/tests/test_hr_expense_payment.py
  hr_expense_tier_validation/tests/test_hr_expense_tier_validation.py
Labels: bot is merging ⏳

#279 [17.0][FIX] hr_expense_*: Fix + improve tests
  hr_expense_cancel/tests/test_hr_expense_cancel.py
  hr_expense_invoice/tests/test_hr_expense_invoice.py
  hr_expense_payment/tests/test_hr_expense_payment.py
Labels: bot is merging ⏳

#276 [17.0][FIX] hr_expense_invoice: Proper partner
  hr_expense_invoice/models/hr_expense_sheet.py
Labels: approved, ready to merge, bot is merging ⏳
